services:
  node:
    env_file:
      - .env
    image: registry.haven1.org/haven1-node:1.1.0
    volumes:
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
      - ../data:/data
      - ./keystore:/keystore:ro
    network_mode: host
    entrypoint: ["sh", "-c", /docker-entrypoint.sh]
    logging:
      driver: json-file
      options:
        max-size: "5G"
        max-file: "3"
  cosigner:
    env_file:
      - .env
    image: registry.haven1.org/cosigner:1.374.0
    entrypoint: ["java", "-jar", "cosigner.jar"]
    network_mode: host
    logging:
      driver: json-file
      options:
        max-size: "5G"
        max-file: "3"
