services:
  node:
    env_file:
      - .env
    image: registry.haven1.org/haven1-node:1.5.0
    volumes:
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
      - ../../data:/data
      - ../keystore:/keystore:ro
    network_mode: host
    restart: always
    entrypoint: ["sh", "-c", /docker-entrypoint.sh]
    logging:
      driver: json-file
      options:
        max-size: "5G"
        max-file: "3"